#!/usr/bin/env bash

set -Eeo pipefail

# shellcheck source=install-shared.bash
source "$(dirname "${BASH_SOURCE[0]}")/install-shared.bash"

subm_dir="bls-signatures"

git submodule update --init --recursive $subm_dir

if download_release_tarball tarball_path "${subm_dir}"; then
    tmp_dir=$(mktemp -d)
    tar -C "$tmp_dir" -xzf "$tarball_path"

    cp "${tmp_dir}/include/libbls_signatures.h" .
    cp "${tmp_dir}/lib/libbls_signatures.a" .
    cp "${tmp_dir}/lib/pkgconfig/libbls_signatures.pc" .
else
    (>&2 echo "failed to find or obtain precompiled assets for ${subm_dir}, falling back to local build")
    build_from_source "${subm_dir}"

    find "${subm_dir}" -type f -name libbls_signatures.h -exec mv -- "{}" . \;
    find "${subm_dir}" -type f -name libbls_signatures_ffi.a -exec cp -- "{}" libbls_signatures.a \;
    find "${subm_dir}" -type f -name libbls_signatures.pc -exec cp -- "{}" . \;
fi
